# Generated by Django 2.0 on 2017-12-25 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_is_active', models.BooleanField(default='True')),
                ('prep_name', models.CharField(max_length=50, verbose_name='Наименование препарата')),
            ],
        ),
        migrations.CreateModel(
            name='PrepImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=64)),
                ('src', models.ImageField(upload_to='%Y/%m/%d/%H/%M/%S/')),
            ],
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zascat.PrepImages'),
        ),
    ]
