# Generated by Django 2.0 on 2017-12-25 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prep',
            options={'verbose_name': 'Препарат', 'verbose_name_plural': 'Препараты'},
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_advert',
            field=models.TextField(null=True, verbose_name='Краткое рекламное описание'),
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления (изменения)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_desc',
            field=models.CharField(default='default', max_length=254, verbose_name='Краткое описание (изготовитель, состав...)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_header',
            field=models.CharField(default='asdasd', max_length=100, verbose_name='Заглавный лозунг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
