# Generated by Django 2.0 on 2017-12-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0002_auto_20171225_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepimages',
            options={'verbose_name': 'Изображение препарата', 'verbose_name_plural': 'Изображения препарата'},
        ),
    ]
