# Generated by Django 2.0 on 2017-12-25 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0003_auto_20171225_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 25, 11, 14, 53, 127761, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_header',
            field=models.TextField(verbose_name='Заглавный лозунг'),
        ),
    ]
