# Generated by Django 2.0 on 2017-12-26 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0004_auto_20171225_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='prep',
            name='prep_apply_how',
            field=models.TextField(default='dasdfs', verbose_name='Как применять'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_apply_why',
            field=models.TextField(default='sfdfsd', verbose_name='Для чего и где применять'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_eco_safe',
            field=models.TextField(default='sadfsdg', verbose_name='Безопасность и экология'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_package_table',
            field=models.TextField(default='sdfsdf', verbose_name='Таблица фасовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_preview_contains',
            field=models.CharField(default='sdfsdf', max_length=200, verbose_name='Состав для предпоказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_preview_desc',
            field=models.TextField(default='sdfsdfs', verbose_name='Описание для предпоказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_result',
            field=models.TextField(default='sdfsdg', verbose_name='Действие и результат'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 26, 10, 30, 26, 830189, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
    ]
