# Generated by Django 2.0 on 2017-12-26 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0005_auto_20171226_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 26, 10, 35, 36, 602202, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
    ]
