# Generated by Django 2.0 on 2017-12-26 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0006_auto_20171226_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prep',
            name='prep_images',
        ),
        migrations.RemoveField(
            model_name='prepimages',
            name='alt',
        ),
        migrations.AddField(
            model_name='prep',
            name='prep_images_srcs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='zascat.PrepImages'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 26, 13, 54, 48, 618364, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_header',
            field=models.CharField(max_length=50, verbose_name='Заглавный лозунг'),
        ),
    ]
