# Generated by Django 2.0 on 2018-07-12 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0007_auto_20171226_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prep',
            name='prep_images_srcs',
        ),
        migrations.AddField(
            model_name='prepimages',
            name='prep_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zascat.Prep'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 8, 52, 6, 84044, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
    ]
