# Generated by Django 2.0 on 2018-07-12 09:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0008_auto_20180712_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 9, 44, 50, 885021, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
        migrations.AlterField(
            model_name='prepimages',
            name='prep_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zascat.Prep'),
        ),
    ]
