# Generated by Django 2.0 on 2018-07-25 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0009_auto_20180712_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepimages',
            name='prep_name',
        ),
        migrations.AddField(
            model_name='prepimages',
            name='prep',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='zascat.Prep'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 25, 9, 37, 15, 472085, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
    ]
