# Generated by Django 2.0 on 2018-07-25 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0010_auto_20180725_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='prep',
            name='prep_eng_name',
            field=models.CharField(default='1', max_length=50, verbose_name='Наименование препарата по английски для красивого URL'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 25, 11, 15, 5, 53814, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
    ]
