# Generated by Django 2.0 on 2018-07-26 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0012_auto_20180726_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepcategory',
            options={'verbose_name': 'Категория препарата', 'verbose_name_plural': 'Категори препаратов'},
        ),
        migrations.RenameField(
            model_name='prepcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 26, 10, 57, 6, 164524, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
    ]
