# Generated by Django 2.0 on 2018-07-26 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0013_auto_20180726_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepcategory',
            name='img',
            field=models.ImageField(default='1', upload_to='%Y/%m/%d/%H/%M/%S/', verbose_name='Картинка для категори'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepcategory',
            name='text',
            field=models.TextField(default='/cat/', max_length=200, verbose_name='Описание категори'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 26, 11, 24, 33, 791881, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
    ]
