# Generated by Django 2.0 on 2018-12-20 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0014_auto_20180726_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 20, 9, 39, 44, 423359, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
    ]
