# Generated by Django 2.0 on 2019-04-03 10:06

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0015_auto_20181220_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prep',
            name='prep_advert',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Краткое рекламное описание'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_apply_how',
            field=ckeditor.fields.RichTextField(verbose_name='Как применять'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_apply_why',
            field=ckeditor.fields.RichTextField(verbose_name='Для чего и где применять'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 3, 10, 6, 33, 102643, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_eco_safe',
            field=ckeditor.fields.RichTextField(verbose_name='Безопасность и экология'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_package_table',
            field=ckeditor.fields.RichTextField(verbose_name='Таблица фасовок'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_preview_desc',
            field=ckeditor.fields.RichTextField(verbose_name='Описание для предпоказа'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_result',
            field=ckeditor.fields.RichTextField(verbose_name='Действие и результат'),
        ),
        migrations.AlterField(
            model_name='prepcategory',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Описание категори'),
        ),
    ]
