# Generated by Django 2.0 on 2019-04-04 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zascat', '0017_auto_20190404_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='prep',
            name='prep_preview_image',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='prep_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 4, 9, 43, 4, 555775, tzinfo=utc), verbose_name='Дата добавления (изменения)'),
        ),
    ]
