# Generated by Django 2.0 on 2017-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_name', models.CharField(max_length=50)),
                ('to_index', models.IntegerField(max_length=6)),
                ('to_street', models.CharField(max_length=254)),
                ('to_region', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=50)),
                ('from_index', models.IntegerField(max_length=6)),
                ('from_street', models.CharField(max_length=254)),
                ('from_region', models.CharField(max_length=254)),
            ],
        ),
    ]
