# Generated by Django 2.0 on 2017-12-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciever',
            name='to_index',
        ),
        migrations.RemoveField(
            model_name='sender',
            name='from_index',
        ),
    ]
