# Generated by Django 2.0 on 2017-12-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0002_auto_20171212_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciever',
            name='to_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reciever',
            name='to_index',
            field=models.IntegerField(null=True, verbose_name='Индекс Получателя: '),
        ),
        migrations.AddField(
            model_name='sender',
            name='from_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sender',
            name='from_index',
            field=models.IntegerField(null=True, verbose_name='Индекс отправителя: '),
        ),
        migrations.AlterField(
            model_name='sender',
            name='from_name',
            field=models.CharField(max_length=50, verbose_name='Кому: '),
        ),
        migrations.AlterField(
            model_name='sender',
            name='from_region',
            field=models.CharField(max_length=254, verbose_name='Страна, Регион, Область: '),
        ),
        migrations.AlterField(
            model_name='sender',
            name='from_street',
            field=models.CharField(max_length=254, verbose_name='Адрес, начиная с улицы: '),
        ),
    ]
