# Generated by Django 2.0 on 2017-12-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0003_auto_20171213_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciever',
            options={'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
        migrations.AlterModelOptions(
            name='sender',
            options={'verbose_name': 'Отправитель', 'verbose_name_plural': 'Отправители'},
        ),
        migrations.AlterField(
            model_name='reciever',
            name='to_index',
            field=models.IntegerField(null=True, verbose_name='Индекс Получателя'),
        ),
        migrations.AlterField(
            model_name='reciever',
            name='to_name',
            field=models.CharField(max_length=50, verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='reciever',
            name='to_region',
            field=models.CharField(max_length=254, verbose_name='Адрес, начиная с улицы'),
        ),
        migrations.AlterField(
            model_name='reciever',
            name='to_street',
            field=models.CharField(max_length=254, verbose_name='Адрес, начиная с улицы'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='from_index',
            field=models.IntegerField(null=True, verbose_name='Индекс отправителя'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='from_name',
            field=models.CharField(max_length=50, verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='from_region',
            field=models.CharField(max_length=254, verbose_name='Страна, Регион, Область'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='from_street',
            field=models.CharField(max_length=254, verbose_name='Адрес, начиная с улицы'),
        ),
    ]
